name: Build RustDesk for Windows (starworld99)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-2022

    env:
      FLUTTER_VERSION: "3.24.0"
      RUST_BACKTRACE: full

    steps:
      - name: Checkout rustdesk source
        uses: actions/checkout@v4
        with:
          submodules: false   # 不拉取原始 hbb_common

      - name: Replace hbb_common with your fork
        shell: pwsh
        run: |
          if (Test-Path libs/hbb_common) { Remove-Item -Recurse -Force libs/hbb_common }
          git clone --depth=1 https://github.com/starworld99/hbb_common.git libs/hbb_common
          dir libs/hbb_common

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Build RustDesk (Windows)
        shell: pwsh
        run: |
          cd flutter
          flutter pub get
          cd ..
          cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
